name: Releasing APK files
runs:
  using: "composite"
  steps:
    - name: Delete existing release
      shell: bash
      run: |
        # Get release ID
        release_id=$(curl -s -H "Authorization: token ${{ github.token }}" \
          "https://api.github.com/repos/${{ github.repository }}/releases/tags/all" | \
          jq -r '.id')
        
        if [ "$release_id" != "null" ]; then
          # Get asset IDs
          asset_ids=$(curl -s -H "Authorization: token ${{ github.token }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/$release_id/assets" | \
            jq -r '.[].id')
          
          # Delete each asset
          for asset_id in $asset_ids; do
            curl -X DELETE -H "Authorization: token ${{ github.token }}" \
              "https://api.github.com/repos/${{ github.repository }}/releases/assets/$asset_id"
          done
        fi
    - name: Generate release info
      shell: bash
      run: |
        echo "
        **Change log** :point_down:
        [Revanced](https://github.com/revanced/revanced-patches/releases)
        [Revanced Extended](https://github.com/inotia00/revanced-patches/releases)
        [Revanced Extended anddea](https://github.com/anddea/revanced-patches/releases)
        [Revanced Extended for Android 6 & 7](https://github.com/kitadai31/revanced-patches-android6-7/releases)
        [Revanced Extended For Android 5:](https://github.com/d4n3436/revanced-patches-android5/releases)
        "> ${{ github.workspace }}-CHANGELOG.txt
    - name: Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: |
          ./release/*.apk
        name: Revanced & Revanced Extended
        tag: all
        bodyFile: ${{ github.workspace }}-CHANGELOG.txt
        allowUpdates: true
        removeArtifacts: true
